# Generated by Django 5.0.7 on 2024-08-04 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("author", models.CharField(max_length=400)),
                ("publishing_company", models.CharField(max_length=100)),
                ("pages", models.IntegerField()),
                ("edition", models.IntegerField()),
            ],
            options={
                "db_table": "library",
                "ordering": ["id"],
            },
        ),
    ]
